### ISSUE TITLE
List Boxes should have Parameter to Map as pilotscript

### ISSUE THREAD

**Issue by arjd** [saberinformatics/plp-semantic-ui#6]
Hi,

Can the default behavior for Parameter to Map for List Boxes in this framework be PilotScript?

Thank you
Adam

**Comment by saberinfo** [comment]
The listbox parameter is set to String Type on the Semantic UI listbox component because the stock component in pipeline pilot has this same parameter as String Type.

If we were to change the type, the component wouldn't serve as a "drop-in replacement" for the default listbox... For that reason it's probably better to keep the parameter as String Type.

To have a dynamic name for this parameter in your code you could would wrap it in a run-to-completion subprotocol and set a global variable just before it then put the global in the parameter as $(variablename). Also of course limit the global's scope to the subprotocol.
